name: flutter_huevo
description: Flutter Huevo app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+2

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Common
  flutter_bloc: ^9.1.0
  loggy: ^2.0.3
  flutter_loggy: ^2.0.3+1
  go_router: ^15.1.1
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  intl: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.5.3
  flutter_keyboard_visibility: ^6.0.0
  mixpanel_flutter: ^2.4.0
  image_picker: ^1.1.2
  in_app_review: ^2.0.10
  google_sign_in: ^6.3.0
  crypto: ^3.0.6
  flutter_local_notifications: ^19.2.0
  dio: ^5.8.0+1
  flutter_loggy_dio: ^3.1.0
  rxdart: ^0.28.0
  collection: ^1.19.1
  flutter_timezone: ^4.1.0
  timezone: ^0.10.1

  # Payment
  purchases_flutter: ^8.7.3

  # Firebase
  firebase_core: ^3.13.0
  firebase_analytics: ^11.4.5
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  cloud_functions: ^5.4.0
  firebase_crashlytics: ^4.3.5
  firebase_remote_config: ^5.4.3
  firebase_storage: ^12.4.7
  firebase_messaging: ^15.2.5

  # iOS
  cupertino_icons: ^1.0.2
  sign_in_with_apple: ^7.0.1
  app_tracking_transparency: ^2.0.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
